[package]
name = "goose-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A terminal user interface for Goose"

[dependencies]
goose = { path = "../goose" }
goose-server = { path = "../goose-server" }
goose-client = { path = "../goose-client" }
rmcp = { workspace = true }
anyhow = "1.0"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
tui-textarea = { version = "0.7.0", features = ["search"] }
tokio = { version = "1.43", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
axum = { version = "0.8.1", features = ["ws", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json", "time"] }
tracing-appender = "0.2"
futures = "0.3"
uuid = { version = "1.11", features = ["fast-rng", "v4"] }
directories = "5.0"
tokio-stream = "0.1.17"
clap = { version = "4.5.52", features = ["derive"] }
goose-mcp = { version = "1.14.0", path = "../goose-mcp" }
termimad = "0.34.0"
unicode-width = "0.2.0"
arboard = "3.6.1"
ansi-to-tui = "7.0.0"
git2 = { version = "0.18", default-features = false }
rustyline = "15"
dirs = "6.0.0"

[dev-dependencies]
chrono = "0.4.42"
tempfile = "3.23.0"
tokio = { version = "1.43", features = ["full"] }
